#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage:
  scripts/ios-personal-testflight-prepare.sh [--build-number 7] [--team-id TEAMID] [--bundle-base BUNDLE_ID]

Prepares a personal TestFlight/App Store Connect build under your own Apple
Developer team. This intentionally does not use the canonical OpenClaw release
team or hosted relay.
EOF
}

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
IOS_DIR="${ROOT_DIR}/apps/ios"
BUILD_DIR="${IOS_DIR}/build"
TEAM_HELPER="${ROOT_DIR}/scripts/ios-team-id.sh"
VERSION_HELPER="${ROOT_DIR}/scripts/ios-write-version-xcconfig.sh"
OUTPUT_XCCONFIG="${BUILD_DIR}/PersonalTestFlight.xcconfig"

BUILD_NUMBER="${IOS_RELEASE_BUILD_NUMBER:-}"
TEAM_ID="${IOS_DEVELOPMENT_TEAM:-}"
BUNDLE_BASE="${OPENCLAW_IOS_APP_BUNDLE_ID:-${OPENCLAW_IOS_BUNDLE_ID_BASE:-}}"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --)
      shift
      ;;
    --build-number)
      BUILD_NUMBER="${2:-}"
      shift 2
      ;;
    --team-id)
      TEAM_ID="${2:-}"
      shift 2
      ;;
    --bundle-base)
      BUNDLE_BASE="${2:-}"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

if [[ -z "${TEAM_ID}" ]]; then
  TEAM_ID="$(IOS_ALLOW_KEYCHAIN_TEAM_FALLBACK=1 "${TEAM_HELPER}")"
fi

if [[ -z "${TEAM_ID}" ]]; then
  echo "Could not resolve Apple Team ID. Set IOS_DEVELOPMENT_TEAM or sign into Xcode." >&2
  exit 1
fi

if [[ -z "${BUNDLE_BASE}" ]]; then
  "${ROOT_DIR}/scripts/ios-configure-signing.sh" >/dev/null
  BUNDLE_BASE="$(
    sed -n 's/^OPENCLAW_APP_BUNDLE_ID = //p' "${IOS_DIR}/.local-signing.xcconfig" | tail -1
  )"
fi

if [[ -z "${BUNDLE_BASE}" ]]; then
  echo "Could not resolve bundle base. Pass --bundle-base, for example com.example.openclaw." >&2
  exit 1
fi

mkdir -p "${BUILD_DIR}"

if [[ -n "${BUILD_NUMBER}" ]]; then
  bash "${VERSION_HELPER}" --build-number "${BUILD_NUMBER}"
else
  bash "${VERSION_HELPER}"
fi

cat >"${OUTPUT_XCCONFIG}" <<EOF
// Auto-generated by scripts/ios-personal-testflight-prepare.sh.
// Local personal TestFlight override; do not commit.
OPENCLAW_CODE_SIGN_STYLE = Automatic
OPENCLAW_CODE_SIGN_IDENTITY = Apple Development
OPENCLAW_DEVELOPMENT_TEAM = ${TEAM_ID}
OPENCLAW_IOS_SELECTED_TEAM = ${TEAM_ID}
OPENCLAW_APP_BUNDLE_ID = ${BUNDLE_BASE}
OPENCLAW_SHARE_BUNDLE_ID = ${BUNDLE_BASE}.share
OPENCLAW_ACTIVITY_WIDGET_BUNDLE_ID = ${BUNDLE_BASE}.activitywidget
OPENCLAW_WATCH_APP_BUNDLE_ID = ${BUNDLE_BASE}.watchkitapp
OPENCLAW_WATCH_EXTENSION_BUNDLE_ID = ${BUNDLE_BASE}.watchkitapp.extension
OPENCLAW_APNS_ENTITLEMENT_ENVIRONMENT = production
OPENCLAW_PUSH_TRANSPORT = direct
OPENCLAW_PUSH_DISTRIBUTION = local
OPENCLAW_PUSH_RELAY_BASE_URL =
OPENCLAW_PUSH_APNS_ENVIRONMENT = production
OPENCLAW_APP_PROFILE =
OPENCLAW_SHARE_PROFILE =
OPENCLAW_ACTIVITY_WIDGET_PROFILE =
OPENCLAW_WATCH_APP_PROFILE =
OPENCLAW_WATCH_EXTENSION_PROFILE =
EOF

(
  cd "${IOS_DIR}"
  xcodegen generate
)

echo "Prepared personal TestFlight build: team=${TEAM_ID} app=${BUNDLE_BASE}"
echo "XCODE_XCCONFIG_FILE=${OUTPUT_XCCONFIG}"
